
export const ShoesData = [
  {
    id: 1,
    img: "	https://themewagon.github.io/stylish/images/card-item3.jpg",
    name: "NIKE",
    price: "$109",
    category: "Male",
  },
  {
    id: 2,
    img: "https://themewagon.github.io/stylish/images/card-item8.jpg",
    name: "New Balance",
    price: "$149",
    category: "Female",
  },
  {
    id: 3,
    img: "	https://themewagon.github.io/stylish/images/card-item7.jpg",
    name: "NIKE",
    price: "$79",
    category: "Male",
  },
  {
    id: 4,
    img: "https://themewagon.github.io/stylish/images/card-item4.jpg",
    name: "NIKE",
    price: "$99",
    category: "Female",
  },
  {
    id: 5,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh50TAPkXI7K6tQ1JnPLfp1QpIAqDnMMTg7Q&s",
    name: " Skechers",
    price: "$119",
    category: "Male",
  },
  {
    id: 6,
    img: "https://themewagon.github.io/stylish/images/card-image1.jpg",
    name: "NIKE",
    price: "$119",
    category: "Male",
  },
  {
    id: 7,
    img: "https://themewagon.github.io/stylish/images/card-image3.jpg",
    name: "Allen Edmonds",
    price: "$89",
    category: "Female",
  },
  {
    id: 8,
    img: "	https://themewagon.github.io/stylish/images/card-item6.jpg",
    name: "Church’s",
    price: "$139",
    category: "Female",
  },
  {
    id: 9,
    img: "https://themewagon.github.io/stylish/images/card-item10.jpg",
    name: "NIKE",
    price: "$99",
    category: "Male",
  },
  {
    id: 10,
    img: "https://paragonfootwear.com/cdn/shop/products/k1016l_pch_1.jpg?v=1741862818",
    name: "Paragon Footwear",
    price: "$129",
    category: "Female",
  },
  {
    id: 11,
    img: "https://themewagon.github.io/stylish/images/card-item1.jpg",
    name: "PUMA",
    price: "$89",
  },
  {
    id: 12,
    img: "https://themewagon.github.io/stylish/images/card-item9.jpg",
    name: "NIKE",
    price: "$99",
  },
  {
    id: 13,
    img: "https://themewagon.github.io/stylish/images/card-item2.jpg",
    name: "NIKE",
    price: "$119",
  },
  {
    id: 14,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe6GV2PnQ8j-kmBW8h2qJunwcVAUOi2OBYfA&s",
    name: "TREX",
    price: "$129",
  },
  {
    id: 14,
    img: "https://affinity.com.pk/cdn/shop/products/image_de69f216-1119-411c-a0e4-ed6e142a425b.jpg?v=1645274467",
    name: "Adidas",
    price: "$129",
  },
];